[package]
name = "r0-baby-bear"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bytemuck = { version = "1.12", features = ["derive"] }
rand_core = "0.6"

[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] }